-- Auto-generated by matugen. Do not edit manually.
local M = {}
M.colors = {
  primary            = "#ffffff",
  on_primary         = "#1b1b1b",
  primary_container  = "#d4d4d4",
  secondary          = "#c6c6c6",
  on_secondary       = "#1b1b1b",
  surface            = "#131313",
  on_surface         = "#e2e2e2",
  surface_variant    = "#474747",
  on_surface_variant = "#c6c6c6",
  background         = "#131313",
  on_background      = "#e2e2e2",
  error              = "#ffb4ab",
  on_error           = "#690005",
  outline            = "#919191",
  outline_variant    = "#474747",
  tertiary           = "#e2e2e2",
  on_tertiary        = "#1b1b1b",
}
return M
